// Copyright (c) 2024 Tencent Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/services/schedulerplugin/v1/plugin.proto

package schedulerplugin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HandshakeRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion string                 `protobuf:"bytes,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	PluginName      string                 `protobuf:"bytes,2,opt,name=plugin_name,json=pluginName,proto3" json:"plugin_name,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HandshakeRequest) Reset() {
	*x = HandshakeRequest{}
	mi := &file_api_services_schedulerplugin_v1_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeRequest) ProtoMessage() {}

func (x *HandshakeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_services_schedulerplugin_v1_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeRequest.ProtoReflect.Descriptor instead.
func (*HandshakeRequest) Descriptor() ([]byte, []int) {
	return file_api_services_schedulerplugin_v1_plugin_proto_rawDescGZIP(), []int{0}
}

func (x *HandshakeRequest) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *HandshakeRequest) GetPluginName() string {
	if x != nil {
		return x.PluginName
	}
	return ""
}

type HandshakeResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion string                 `protobuf:"bytes,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	PluginName      string                 `protobuf:"bytes,2,opt,name=plugin_name,json=pluginName,proto3" json:"plugin_name,omitempty"`
	Capabilities    []string               `protobuf:"bytes,3,rep,name=capabilities,proto3" json:"capabilities,omitempty"` // "filter" and/or "score"
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HandshakeResponse) Reset() {
	*x = HandshakeResponse{}
	mi := &file_api_services_schedulerplugin_v1_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeResponse) ProtoMessage() {}

func (x *HandshakeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_services_schedulerplugin_v1_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeResponse.ProtoReflect.Descriptor instead.
func (*HandshakeResponse) Descriptor() ([]byte, []int) {
	return file_api_services_schedulerplugin_v1_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *HandshakeResponse) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *HandshakeResponse) GetPluginName() string {
	if x != nil {
		return x.PluginName
	}
	return ""
}

func (x *HandshakeResponse) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type RequestContext struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	InstanceType   string                 `protobuf:"bytes,1,opt,name=instance_type,json=instanceType,proto3" json:"instance_type,omitempty"`
	CpuMillis      int64                  `protobuf:"varint,2,opt,name=cpu_millis,json=cpuMillis,proto3" json:"cpu_millis,omitempty"`
	MemoryBytes    int64                  `protobuf:"varint,3,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	SystemDiskSize int64                  `protobuf:"varint,4,opt,name=system_disk_size,json=systemDiskSize,proto3" json:"system_disk_size,omitempty"`
	TemplateId     string                 `protobuf:"bytes,5,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	Labels         map[string]string      `protobuf:"bytes,6,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RequestContext) Reset() {
	*x = RequestContext{}
	mi := &file_api_services_schedulerplugin_v1_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestContext) ProtoMessage() {}

func (x *RequestContext) ProtoReflect() protoreflect.Message {
	mi := &file_api_services_schedulerplugin_v1_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestContext.ProtoReflect.Descriptor instead.
func (*RequestContext) Descriptor() ([]byte, []int) {
	return file_api_services_schedulerplugin_v1_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *RequestContext) GetInstanceType() string {
	if x != nil {
		return x.InstanceType
	}
	return ""
}

func (x *RequestContext) GetCpuMillis() int64 {
	if x != nil {
		return x.CpuMillis
	}
	return 0
}

func (x *RequestContext) GetMemoryBytes() int64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *RequestContext) GetSystemDiskSize() int64 {
	if x != nil {
		return x.SystemDiskSize
	}
	return 0
}

func (x *RequestContext) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *RequestContext) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type SnapshotNode struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Id                      string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Ip                      string                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Healthy                 bool                   `protobuf:"varint,3,opt,name=healthy,proto3" json:"healthy,omitempty"`
	CpuTotal                int64                  `protobuf:"varint,4,opt,name=cpu_total,json=cpuTotal,proto3" json:"cpu_total,omitempty"`
	CpuUtil                 float64                `protobuf:"fixed64,5,opt,name=cpu_util,json=cpuUtil,proto3" json:"cpu_util,omitempty"`
	CpuLoad                 float64                `protobuf:"fixed64,6,opt,name=cpu_load,json=cpuLoad,proto3" json:"cpu_load,omitempty"`
	MemTotalMb              int64                  `protobuf:"varint,7,opt,name=mem_total_mb,json=memTotalMb,proto3" json:"mem_total_mb,omitempty"`
	MemUsageMb              int64                  `protobuf:"varint,8,opt,name=mem_usage_mb,json=memUsageMb,proto3" json:"mem_usage_mb,omitempty"`
	QuotaCpu                int64                  `protobuf:"varint,9,opt,name=quota_cpu,json=quotaCpu,proto3" json:"quota_cpu,omitempty"`
	AllocatedCpu            int64                  `protobuf:"varint,10,opt,name=allocated_cpu,json=allocatedCpu,proto3" json:"allocated_cpu,omitempty"`
	QuotaMemMb              int64                  `protobuf:"varint,11,opt,name=quota_mem_mb,json=quotaMemMb,proto3" json:"quota_mem_mb,omitempty"`
	AllocatedMemMb          int64                  `protobuf:"varint,12,opt,name=allocated_mem_mb,json=allocatedMemMb,proto3" json:"allocated_mem_mb,omitempty"`
	Creating                int64                  `protobuf:"varint,13,opt,name=creating,proto3" json:"creating,omitempty"`
	LocalCreating           int64                  `protobuf:"varint,14,opt,name=local_creating,json=localCreating,proto3" json:"local_creating,omitempty"`
	MvmNum                  int64                  `protobuf:"varint,15,opt,name=mvm_num,json=mvmNum,proto3" json:"mvm_num,omitempty"`
	SystemDiskSize          int64                  `protobuf:"varint,16,opt,name=system_disk_size,json=systemDiskSize,proto3" json:"system_disk_size,omitempty"`
	DataDiskUsage           float64                `protobuf:"fixed64,17,opt,name=data_disk_usage,json=dataDiskUsage,proto3" json:"data_disk_usage,omitempty"`
	StorageDiskUsage        float64                `protobuf:"fixed64,18,opt,name=storage_disk_usage,json=storageDiskUsage,proto3" json:"storage_disk_usage,omitempty"`
	SystemDiskUsage         float64                `protobuf:"fixed64,19,opt,name=system_disk_usage,json=systemDiskUsage,proto3" json:"system_disk_usage,omitempty"`
	Labels                  map[string]string      `protobuf:"bytes,20,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	LocalTemplates          []string               `protobuf:"bytes,21,rep,name=local_templates,json=localTemplates,proto3" json:"local_templates,omitempty"`
	TemplateLocal           bool                   `protobuf:"varint,22,opt,name=template_local,json=templateLocal,proto3" json:"template_local,omitempty"`
	SnapshotStorageWritable bool                   `protobuf:"varint,23,opt,name=snapshot_storage_writable,json=snapshotStorageWritable,proto3" json:"snapshot_storage_writable,omitempty"`
	Reserved                int64                  `protobuf:"varint,24,opt,name=reserved,proto3" json:"reserved,omitempty"` // in-flight reservation, populated when reservation management is enabled
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *SnapshotNode) Reset() {
	*x = SnapshotNode{}
	mi := &file_api_services_schedulerplugin_v1_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotNode) ProtoMessage() {}

func (x *SnapshotNode) ProtoReflect() protoreflect.Message {
	mi := &file_api_services_schedulerplugin_v1_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotNode.ProtoReflect.Descriptor instead.
func (*SnapshotNode) Descriptor() ([]byte, []int) {
	return file_api_services_schedulerplugin_v1_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *SnapshotNode) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SnapshotNode) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *SnapshotNode) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *SnapshotNode) GetCpuTotal() int64 {
	if x != nil {
		return x.CpuTotal
	}
	return 0
}

func (x *SnapshotNode) GetCpuUtil() float64 {
	if x != nil {
		return x.CpuUtil
	}
	return 0
}

func (x *SnapshotNode) GetCpuLoad() float64 {
	if x != nil {
		return x.CpuLoad
	}
	return 0
}

func (x *SnapshotNode) GetMemTotalMb() int64 {
	if x != nil {
		return x.MemTotalMb
	}
	return 0
}

func (x *SnapshotNode) GetMemUsageMb() int64 {
	if x != nil {
		return x.MemUsageMb
	}
	return 0
}

func (x *SnapshotNode) GetQuotaCpu() int64 {
	if x != nil {
		return x.QuotaCpu
	}
	return 0
}

func (x *SnapshotNode) GetAllocatedCpu() int64 {
	if x != nil {
		return x.AllocatedCpu
	}
	return 0
}

func (x *SnapshotNode) GetQuotaMemMb() int64 {
	if x != nil {
		return x.QuotaMemMb
	}
	return 0
}

func (x *SnapshotNode) GetAllocatedMemMb() int64 {
	if x != nil {
		return x.AllocatedMemMb
	}
	return 0
}

func (x *SnapshotNode) GetCreating() int64 {
	if x != nil {
		return x.Creating
	}
	return 0
}

func (x *SnapshotNode) GetLocalCreating() int64 {
	if x != nil {
		return x.LocalCreating
	}
	return 0
}

func (x *SnapshotNode) GetMvmNum() int64 {
	if x != nil {
		return x.MvmNum
	}
	return 0
}

func (x *SnapshotNode) GetSystemDiskSize() int64 {
	if x != nil {
		return x.SystemDiskSize
	}
	return 0
}

func (x *SnapshotNode) GetDataDiskUsage() float64 {
	if x != nil {
		return x.DataDiskUsage
	}
	return 0
}

func (x *SnapshotNode) GetStorageDiskUsage() float64 {
	if x != nil {
		return x.StorageDiskUsage
	}
	return 0
}

func (x *SnapshotNode) GetSystemDiskUsage() float64 {
	if x != nil {
		return x.SystemDiskUsage
	}
	return 0
}

func (x *SnapshotNode) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *SnapshotNode) GetLocalTemplates() []string {
	if x != nil {
		return x.LocalTemplates
	}
	return nil
}

func (x *SnapshotNode) GetTemplateLocal() bool {
	if x != nil {
		return x.TemplateLocal
	}
	return false
}

func (x *SnapshotNode) GetSnapshotStorageWritable() bool {
	if x != nil {
		return x.SnapshotStorageWritable
	}
	return false
}

func (x *SnapshotNode) GetReserved() int64 {
	if x != nil {
		return x.Reserved
	}
	return 0
}

type SnapshotRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SnapshotVersion string                 `protobuf:"bytes,1,opt,name=snapshot_version,json=snapshotVersion,proto3" json:"snapshot_version,omitempty"`
	Nodes           []*SnapshotNode        `protobuf:"bytes,2,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SnapshotRequest) Reset() {
	*x = SnapshotRequest{}
	mi := &file_api_services_schedulerplugin_v1_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotRequest) ProtoMessage() {}

func (x *SnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_services_schedulerplugin_v1_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotRequest.ProtoReflect.Descriptor instead.
func (*SnapshotRequest) Descriptor() ([]byte, []int) {
	return file_api_services_schedulerplugin_v1_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *SnapshotRequest) GetSnapshotVersion() string {
	if x != nil {
		return x.SnapshotVersion
	}
	return ""
}

func (x *SnapshotRequest) GetNodes() []*SnapshotNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type SnapshotResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SnapshotVersion string                 `protobuf:"bytes,1,opt,name=snapshot_version,json=snapshotVersion,proto3" json:"snapshot_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SnapshotResponse) Reset() {
	*x = SnapshotResponse{}
	mi := &file_api_services_schedulerplugin_v1_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotResponse) ProtoMessage() {}

func (x *SnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_services_schedulerplugin_v1_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotResponse.ProtoReflect.Descriptor instead.
func (*SnapshotResponse) Descriptor() ([]byte, []int) {
	return file_api_services_schedulerplugin_v1_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *SnapshotResponse) GetSnapshotVersion() string {
	if x != nil {
		return x.SnapshotVersion
	}
	return ""
}

type FilterRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SnapshotVersion string                 `protobuf:"bytes,1,opt,name=snapshot_version,json=snapshotVersion,proto3" json:"snapshot_version,omitempty"`
	Request         *RequestContext        `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	CandidateIds    []string               `protobuf:"bytes,3,rep,name=candidate_ids,json=candidateIds,proto3" json:"candidate_ids,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FilterRequest) Reset() {
	*x = FilterRequest{}
	mi := &file_api_services_schedulerplugin_v1_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterRequest) ProtoMessage() {}

func (x *FilterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_services_schedulerplugin_v1_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterRequest.ProtoReflect.Descriptor instead.
func (*FilterRequest) Descriptor() ([]byte, []int) {
	return file_api_services_schedulerplugin_v1_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *FilterRequest) GetSnapshotVersion() string {
	if x != nil {
		return x.SnapshotVersion
	}
	return ""
}

func (x *FilterRequest) GetRequest() *RequestContext {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *FilterRequest) GetCandidateIds() []string {
	if x != nil {
		return x.CandidateIds
	}
	return nil
}

type FilterResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SnapshotVersion string                 `protobuf:"bytes,1,opt,name=snapshot_version,json=snapshotVersion,proto3" json:"snapshot_version,omitempty"`
	KeptIds         []string               `protobuf:"bytes,2,rep,name=kept_ids,json=keptIds,proto3" json:"kept_ids,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FilterResponse) Reset() {
	*x = FilterResponse{}
	mi := &file_api_services_schedulerplugin_v1_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterResponse) ProtoMessage() {}

func (x *FilterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_services_schedulerplugin_v1_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterResponse.ProtoReflect.Descriptor instead.
func (*FilterResponse) Descriptor() ([]byte, []int) {
	return file_api_services_schedulerplugin_v1_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *FilterResponse) GetSnapshotVersion() string {
	if x != nil {
		return x.SnapshotVersion
	}
	return ""
}

func (x *FilterResponse) GetKeptIds() []string {
	if x != nil {
		return x.KeptIds
	}
	return nil
}

type ScoreRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SnapshotVersion string                 `protobuf:"bytes,1,opt,name=snapshot_version,json=snapshotVersion,proto3" json:"snapshot_version,omitempty"`
	Request         *RequestContext        `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	CandidateIds    []string               `protobuf:"bytes,3,rep,name=candidate_ids,json=candidateIds,proto3" json:"candidate_ids,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ScoreRequest) Reset() {
	*x = ScoreRequest{}
	mi := &file_api_services_schedulerplugin_v1_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreRequest) ProtoMessage() {}

func (x *ScoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_services_schedulerplugin_v1_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreRequest.ProtoReflect.Descriptor instead.
func (*ScoreRequest) Descriptor() ([]byte, []int) {
	return file_api_services_schedulerplugin_v1_plugin_proto_rawDescGZIP(), []int{8}
}

func (x *ScoreRequest) GetSnapshotVersion() string {
	if x != nil {
		return x.SnapshotVersion
	}
	return ""
}

func (x *ScoreRequest) GetRequest() *RequestContext {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *ScoreRequest) GetCandidateIds() []string {
	if x != nil {
		return x.CandidateIds
	}
	return nil
}

type NodeScore struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Score         float64                `protobuf:"fixed64,2,opt,name=score,proto3" json:"score,omitempty"` // normalized to [0,100]
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeScore) Reset() {
	*x = NodeScore{}
	mi := &file_api_services_schedulerplugin_v1_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeScore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeScore) ProtoMessage() {}

func (x *NodeScore) ProtoReflect() protoreflect.Message {
	mi := &file_api_services_schedulerplugin_v1_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeScore.ProtoReflect.Descriptor instead.
func (*NodeScore) Descriptor() ([]byte, []int) {
	return file_api_services_schedulerplugin_v1_plugin_proto_rawDescGZIP(), []int{9}
}

func (x *NodeScore) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeScore) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

type ScoreResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SnapshotVersion string                 `protobuf:"bytes,1,opt,name=snapshot_version,json=snapshotVersion,proto3" json:"snapshot_version,omitempty"`
	Scores          []*NodeScore           `protobuf:"bytes,2,rep,name=scores,proto3" json:"scores,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ScoreResponse) Reset() {
	*x = ScoreResponse{}
	mi := &file_api_services_schedulerplugin_v1_plugin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreResponse) ProtoMessage() {}

func (x *ScoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_services_schedulerplugin_v1_plugin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreResponse.ProtoReflect.Descriptor instead.
func (*ScoreResponse) Descriptor() ([]byte, []int) {
	return file_api_services_schedulerplugin_v1_plugin_proto_rawDescGZIP(), []int{10}
}

func (x *ScoreResponse) GetSnapshotVersion() string {
	if x != nil {
		return x.SnapshotVersion
	}
	return ""
}

func (x *ScoreResponse) GetScores() []*NodeScore {
	if x != nil {
		return x.Scores
	}
	return nil
}

var File_api_services_schedulerplugin_v1_plugin_proto protoreflect.FileDescriptor

const file_api_services_schedulerplugin_v1_plugin_proto_rawDesc = "" +
	"\n" +
	",api/services/schedulerplugin/v1/plugin.proto\x12\x17cube.schedulerplugin.v1\"^\n" +
	"\x10HandshakeRequest\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\tR\x0fprotocolVersion\x12\x1f\n" +
	"\vplugin_name\x18\x02 \x01(\tR\n" +
	"pluginName\"\x83\x01\n" +
	"\x11HandshakeResponse\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\tR\x0fprotocolVersion\x12\x1f\n" +
	"\vplugin_name\x18\x02 \x01(\tR\n" +
	"pluginName\x12\"\n" +
	"\fcapabilities\x18\x03 \x03(\tR\fcapabilities\"\xca\x02\n" +
	"\x0eRequestContext\x12#\n" +
	"\rinstance_type\x18\x01 \x01(\tR\finstanceType\x12\x1d\n" +
	"\n" +
	"cpu_millis\x18\x02 \x01(\x03R\tcpuMillis\x12!\n" +
	"\fmemory_bytes\x18\x03 \x01(\x03R\vmemoryBytes\x12(\n" +
	"\x10system_disk_size\x18\x04 \x01(\x03R\x0esystemDiskSize\x12\x1f\n" +
	"\vtemplate_id\x18\x05 \x01(\tR\n" +
	"templateId\x12K\n" +
	"\x06labels\x18\x06 \x03(\v23.cube.schedulerplugin.v1.RequestContext.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa3\a\n" +
	"\fSnapshotNode\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\tR\x02ip\x12\x18\n" +
	"\ahealthy\x18\x03 \x01(\bR\ahealthy\x12\x1b\n" +
	"\tcpu_total\x18\x04 \x01(\x03R\bcpuTotal\x12\x19\n" +
	"\bcpu_util\x18\x05 \x01(\x01R\acpuUtil\x12\x19\n" +
	"\bcpu_load\x18\x06 \x01(\x01R\acpuLoad\x12 \n" +
	"\fmem_total_mb\x18\a \x01(\x03R\n" +
	"memTotalMb\x12 \n" +
	"\fmem_usage_mb\x18\b \x01(\x03R\n" +
	"memUsageMb\x12\x1b\n" +
	"\tquota_cpu\x18\t \x01(\x03R\bquotaCpu\x12#\n" +
	"\rallocated_cpu\x18\n" +
	" \x01(\x03R\fallocatedCpu\x12 \n" +
	"\fquota_mem_mb\x18\v \x01(\x03R\n" +
	"quotaMemMb\x12(\n" +
	"\x10allocated_mem_mb\x18\f \x01(\x03R\x0eallocatedMemMb\x12\x1a\n" +
	"\bcreating\x18\r \x01(\x03R\bcreating\x12%\n" +
	"\x0elocal_creating\x18\x0e \x01(\x03R\rlocalCreating\x12\x17\n" +
	"\amvm_num\x18\x0f \x01(\x03R\x06mvmNum\x12(\n" +
	"\x10system_disk_size\x18\x10 \x01(\x03R\x0esystemDiskSize\x12&\n" +
	"\x0fdata_disk_usage\x18\x11 \x01(\x01R\rdataDiskUsage\x12,\n" +
	"\x12storage_disk_usage\x18\x12 \x01(\x01R\x10storageDiskUsage\x12*\n" +
	"\x11system_disk_usage\x18\x13 \x01(\x01R\x0fsystemDiskUsage\x12I\n" +
	"\x06labels\x18\x14 \x03(\v21.cube.schedulerplugin.v1.SnapshotNode.LabelsEntryR\x06labels\x12'\n" +
	"\x0flocal_templates\x18\x15 \x03(\tR\x0elocalTemplates\x12%\n" +
	"\x0etemplate_local\x18\x16 \x01(\bR\rtemplateLocal\x12:\n" +
	"\x19snapshot_storage_writable\x18\x17 \x01(\bR\x17snapshotStorageWritable\x12\x1a\n" +
	"\breserved\x18\x18 \x01(\x03R\breserved\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"y\n" +
	"\x0fSnapshotRequest\x12)\n" +
	"\x10snapshot_version\x18\x01 \x01(\tR\x0fsnapshotVersion\x12;\n" +
	"\x05nodes\x18\x02 \x03(\v2%.cube.schedulerplugin.v1.SnapshotNodeR\x05nodes\"=\n" +
	"\x10SnapshotResponse\x12)\n" +
	"\x10snapshot_version\x18\x01 \x01(\tR\x0fsnapshotVersion\"\xa2\x01\n" +
	"\rFilterRequest\x12)\n" +
	"\x10snapshot_version\x18\x01 \x01(\tR\x0fsnapshotVersion\x12A\n" +
	"\arequest\x18\x02 \x01(\v2'.cube.schedulerplugin.v1.RequestContextR\arequest\x12#\n" +
	"\rcandidate_ids\x18\x03 \x03(\tR\fcandidateIds\"V\n" +
	"\x0eFilterResponse\x12)\n" +
	"\x10snapshot_version\x18\x01 \x01(\tR\x0fsnapshotVersion\x12\x19\n" +
	"\bkept_ids\x18\x02 \x03(\tR\akeptIds\"\xa1\x01\n" +
	"\fScoreRequest\x12)\n" +
	"\x10snapshot_version\x18\x01 \x01(\tR\x0fsnapshotVersion\x12A\n" +
	"\arequest\x18\x02 \x01(\v2'.cube.schedulerplugin.v1.RequestContextR\arequest\x12#\n" +
	"\rcandidate_ids\x18\x03 \x03(\tR\fcandidateIds\":\n" +
	"\tNodeScore\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x01R\x05score\"v\n" +
	"\rScoreResponse\x12)\n" +
	"\x10snapshot_version\x18\x01 \x01(\tR\x0fsnapshotVersion\x12:\n" +
	"\x06scores\x18\x02 \x03(\v2\".cube.schedulerplugin.v1.NodeScoreR\x06scores2\x8d\x03\n" +
	"\x0fSchedulerPlugin\x12b\n" +
	"\tHandshake\x12).cube.schedulerplugin.v1.HandshakeRequest\x1a*.cube.schedulerplugin.v1.HandshakeResponse\x12c\n" +
	"\fSyncSnapshot\x12(.cube.schedulerplugin.v1.SnapshotRequest\x1a).cube.schedulerplugin.v1.SnapshotResponse\x12Y\n" +
	"\x06Filter\x12&.cube.schedulerplugin.v1.FilterRequest\x1a'.cube.schedulerplugin.v1.FilterResponse\x12V\n" +
	"\x05Score\x12%.cube.schedulerplugin.v1.ScoreRequest\x1a&.cube.schedulerplugin.v1.ScoreResponseB`Z^github.com/tencentcloud/CubeSandbox/CubeMaster/api/services/schedulerplugin/v1;schedulerpluginb\x06proto3"

var (
	file_api_services_schedulerplugin_v1_plugin_proto_rawDescOnce sync.Once
	file_api_services_schedulerplugin_v1_plugin_proto_rawDescData []byte
)

func file_api_services_schedulerplugin_v1_plugin_proto_rawDescGZIP() []byte {
	file_api_services_schedulerplugin_v1_plugin_proto_rawDescOnce.Do(func() {
		file_api_services_schedulerplugin_v1_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_services_schedulerplugin_v1_plugin_proto_rawDesc), len(file_api_services_schedulerplugin_v1_plugin_proto_rawDesc)))
	})
	return file_api_services_schedulerplugin_v1_plugin_proto_rawDescData
}

var file_api_services_schedulerplugin_v1_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_api_services_schedulerplugin_v1_plugin_proto_goTypes = []any{
	(*HandshakeRequest)(nil),  // 0: cube.schedulerplugin.v1.HandshakeRequest
	(*HandshakeResponse)(nil), // 1: cube.schedulerplugin.v1.HandshakeResponse
	(*RequestContext)(nil),    // 2: cube.schedulerplugin.v1.RequestContext
	(*SnapshotNode)(nil),      // 3: cube.schedulerplugin.v1.SnapshotNode
	(*SnapshotRequest)(nil),   // 4: cube.schedulerplugin.v1.SnapshotRequest
	(*SnapshotResponse)(nil),  // 5: cube.schedulerplugin.v1.SnapshotResponse
	(*FilterRequest)(nil),     // 6: cube.schedulerplugin.v1.FilterRequest
	(*FilterResponse)(nil),    // 7: cube.schedulerplugin.v1.FilterResponse
	(*ScoreRequest)(nil),      // 8: cube.schedulerplugin.v1.ScoreRequest
	(*NodeScore)(nil),         // 9: cube.schedulerplugin.v1.NodeScore
	(*ScoreResponse)(nil),     // 10: cube.schedulerplugin.v1.ScoreResponse
	nil,                       // 11: cube.schedulerplugin.v1.RequestContext.LabelsEntry
	nil,                       // 12: cube.schedulerplugin.v1.SnapshotNode.LabelsEntry
}
var file_api_services_schedulerplugin_v1_plugin_proto_depIdxs = []int32{
	11, // 0: cube.schedulerplugin.v1.RequestContext.labels:type_name -> cube.schedulerplugin.v1.RequestContext.LabelsEntry
	12, // 1: cube.schedulerplugin.v1.SnapshotNode.labels:type_name -> cube.schedulerplugin.v1.SnapshotNode.LabelsEntry
	3,  // 2: cube.schedulerplugin.v1.SnapshotRequest.nodes:type_name -> cube.schedulerplugin.v1.SnapshotNode
	2,  // 3: cube.schedulerplugin.v1.FilterRequest.request:type_name -> cube.schedulerplugin.v1.RequestContext
	2,  // 4: cube.schedulerplugin.v1.ScoreRequest.request:type_name -> cube.schedulerplugin.v1.RequestContext
	9,  // 5: cube.schedulerplugin.v1.ScoreResponse.scores:type_name -> cube.schedulerplugin.v1.NodeScore
	0,  // 6: cube.schedulerplugin.v1.SchedulerPlugin.Handshake:input_type -> cube.schedulerplugin.v1.HandshakeRequest
	4,  // 7: cube.schedulerplugin.v1.SchedulerPlugin.SyncSnapshot:input_type -> cube.schedulerplugin.v1.SnapshotRequest
	6,  // 8: cube.schedulerplugin.v1.SchedulerPlugin.Filter:input_type -> cube.schedulerplugin.v1.FilterRequest
	8,  // 9: cube.schedulerplugin.v1.SchedulerPlugin.Score:input_type -> cube.schedulerplugin.v1.ScoreRequest
	1,  // 10: cube.schedulerplugin.v1.SchedulerPlugin.Handshake:output_type -> cube.schedulerplugin.v1.HandshakeResponse
	5,  // 11: cube.schedulerplugin.v1.SchedulerPlugin.SyncSnapshot:output_type -> cube.schedulerplugin.v1.SnapshotResponse
	7,  // 12: cube.schedulerplugin.v1.SchedulerPlugin.Filter:output_type -> cube.schedulerplugin.v1.FilterResponse
	10, // 13: cube.schedulerplugin.v1.SchedulerPlugin.Score:output_type -> cube.schedulerplugin.v1.ScoreResponse
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_api_services_schedulerplugin_v1_plugin_proto_init() }
func file_api_services_schedulerplugin_v1_plugin_proto_init() {
	if File_api_services_schedulerplugin_v1_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_services_schedulerplugin_v1_plugin_proto_rawDesc), len(file_api_services_schedulerplugin_v1_plugin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_services_schedulerplugin_v1_plugin_proto_goTypes,
		DependencyIndexes: file_api_services_schedulerplugin_v1_plugin_proto_depIdxs,
		MessageInfos:      file_api_services_schedulerplugin_v1_plugin_proto_msgTypes,
	}.Build()
	File_api_services_schedulerplugin_v1_plugin_proto = out.File
	file_api_services_schedulerplugin_v1_plugin_proto_goTypes = nil
	file_api_services_schedulerplugin_v1_plugin_proto_depIdxs = nil
}
