// Copyright (c) 2024 Tencent Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: api/services/schedulerplugin/v1/plugin.proto

package schedulerplugin

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SchedulerPlugin_Handshake_FullMethodName    = "/cube.schedulerplugin.v1.SchedulerPlugin/Handshake"
	SchedulerPlugin_SyncSnapshot_FullMethodName = "/cube.schedulerplugin.v1.SchedulerPlugin/SyncSnapshot"
	SchedulerPlugin_Filter_FullMethodName       = "/cube.schedulerplugin.v1.SchedulerPlugin/Filter"
	SchedulerPlugin_Score_FullMethodName        = "/cube.schedulerplugin.v1.SchedulerPlugin/Score"
)

// SchedulerPluginClient is the client API for SchedulerPlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SchedulerPlugin is a versioned, batch-oriented extension API. Snapshot data
// is synchronized independently; per-request calls carry only the snapshot
// version, request context and candidate IDs.
type SchedulerPluginClient interface {
	Handshake(ctx context.Context, in *HandshakeRequest, opts ...grpc.CallOption) (*HandshakeResponse, error)
	SyncSnapshot(ctx context.Context, in *SnapshotRequest, opts ...grpc.CallOption) (*SnapshotResponse, error)
	Filter(ctx context.Context, in *FilterRequest, opts ...grpc.CallOption) (*FilterResponse, error)
	Score(ctx context.Context, in *ScoreRequest, opts ...grpc.CallOption) (*ScoreResponse, error)
}

type schedulerPluginClient struct {
	cc grpc.ClientConnInterface
}

func NewSchedulerPluginClient(cc grpc.ClientConnInterface) SchedulerPluginClient {
	return &schedulerPluginClient{cc}
}

func (c *schedulerPluginClient) Handshake(ctx context.Context, in *HandshakeRequest, opts ...grpc.CallOption) (*HandshakeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HandshakeResponse)
	err := c.cc.Invoke(ctx, SchedulerPlugin_Handshake_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerPluginClient) SyncSnapshot(ctx context.Context, in *SnapshotRequest, opts ...grpc.CallOption) (*SnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SnapshotResponse)
	err := c.cc.Invoke(ctx, SchedulerPlugin_SyncSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerPluginClient) Filter(ctx context.Context, in *FilterRequest, opts ...grpc.CallOption) (*FilterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FilterResponse)
	err := c.cc.Invoke(ctx, SchedulerPlugin_Filter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerPluginClient) Score(ctx context.Context, in *ScoreRequest, opts ...grpc.CallOption) (*ScoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScoreResponse)
	err := c.cc.Invoke(ctx, SchedulerPlugin_Score_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SchedulerPluginServer is the server API for SchedulerPlugin service.
// All implementations must embed UnimplementedSchedulerPluginServer
// for forward compatibility.
//
// SchedulerPlugin is a versioned, batch-oriented extension API. Snapshot data
// is synchronized independently; per-request calls carry only the snapshot
// version, request context and candidate IDs.
type SchedulerPluginServer interface {
	Handshake(context.Context, *HandshakeRequest) (*HandshakeResponse, error)
	SyncSnapshot(context.Context, *SnapshotRequest) (*SnapshotResponse, error)
	Filter(context.Context, *FilterRequest) (*FilterResponse, error)
	Score(context.Context, *ScoreRequest) (*ScoreResponse, error)
	mustEmbedUnimplementedSchedulerPluginServer()
}

// UnimplementedSchedulerPluginServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSchedulerPluginServer struct{}

func (UnimplementedSchedulerPluginServer) Handshake(context.Context, *HandshakeRequest) (*HandshakeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Handshake not implemented")
}
func (UnimplementedSchedulerPluginServer) SyncSnapshot(context.Context, *SnapshotRequest) (*SnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncSnapshot not implemented")
}
func (UnimplementedSchedulerPluginServer) Filter(context.Context, *FilterRequest) (*FilterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Filter not implemented")
}
func (UnimplementedSchedulerPluginServer) Score(context.Context, *ScoreRequest) (*ScoreResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Score not implemented")
}
func (UnimplementedSchedulerPluginServer) mustEmbedUnimplementedSchedulerPluginServer() {}
func (UnimplementedSchedulerPluginServer) testEmbeddedByValue()                         {}

// UnsafeSchedulerPluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SchedulerPluginServer will
// result in compilation errors.
type UnsafeSchedulerPluginServer interface {
	mustEmbedUnimplementedSchedulerPluginServer()
}

func RegisterSchedulerPluginServer(s grpc.ServiceRegistrar, srv SchedulerPluginServer) {
	// If the following call panics, it indicates UnimplementedSchedulerPluginServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SchedulerPlugin_ServiceDesc, srv)
}

func _SchedulerPlugin_Handshake_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandshakeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerPluginServer).Handshake(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchedulerPlugin_Handshake_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerPluginServer).Handshake(ctx, req.(*HandshakeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchedulerPlugin_SyncSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerPluginServer).SyncSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchedulerPlugin_SyncSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerPluginServer).SyncSnapshot(ctx, req.(*SnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchedulerPlugin_Filter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FilterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerPluginServer).Filter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchedulerPlugin_Filter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerPluginServer).Filter(ctx, req.(*FilterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchedulerPlugin_Score_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerPluginServer).Score(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchedulerPlugin_Score_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerPluginServer).Score(ctx, req.(*ScoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SchedulerPlugin_ServiceDesc is the grpc.ServiceDesc for SchedulerPlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SchedulerPlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cube.schedulerplugin.v1.SchedulerPlugin",
	HandlerType: (*SchedulerPluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Handshake",
			Handler:    _SchedulerPlugin_Handshake_Handler,
		},
		{
			MethodName: "SyncSnapshot",
			Handler:    _SchedulerPlugin_SyncSnapshot_Handler,
		},
		{
			MethodName: "Filter",
			Handler:    _SchedulerPlugin_Filter_Handler,
		},
		{
			MethodName: "Score",
			Handler:    _SchedulerPlugin_Score_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/services/schedulerplugin/v1/plugin.proto",
}
